name: Setup numba-dppy
description: 'Setup conda environment, build numba-dppy and setup devices'
inputs:
  environment:
    description: Environment file
    required: true
    default: environment/dev.yml
runs:
  using: "composite"
  steps:
    - name: Setup conda
      run: echo $CONDA/bin >> $GITHUB_PATH
      shell: bash

    - name: Setup conda environment
      run: conda env update -n base -f ${{ inputs.environment }} --prune
      shell: bash

    - name: Build numba-dppy
      run: |
        export PATH=$CONDA/bin-llvm:$PATH
        python setup.py develop
      shell: bash

    - name: Setup OpenCL CPU device
      run: echo "OCL_ICD_FILENAMES=libintelocl.so" >> $GITHUB_ENV
      shell: bash
