[tool.black]
exclude = "versioneer.py|numba_dpex/_version.py"
line-length = 80

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80
skip = ["versioneer.py", "numba_dpex/_version.py"]

[tool.coverage.run]
branch = true
source = [
    "numba_dpex"
]
omit = [
    "numba_dpex/tests/*",
    "numba_dpex/_version.py",
]
concurrency = [
    "multiprocessing",
]
parallel = true

[tool.coverage.report]
precision = 2
omit = [
    "numba_dpex/tests/*",
    "numba_dpex/_version.py",
]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError",
  "if config.DEBUG:",
  "@register_jitable",
  "def dpnp_impl",
]
