name: Setup anaconda-client
description: 'Activate conda and install anaconda-client'
runs:
  using: "composite"
  steps:
    - run: echo $CONDA/bin >> $GITHUB_PATH
      shell: bash
    - run: conda install anaconda-client
      shell: bash
