# SPDX-FileCopyrightText: 2023 - 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

"""
Implements the SPIR-V overloads for the kernel_api.items class methods.
"""

from numba.core import types
from numba.core.errors import TypingError
from numba.extending import intrinsic, overload_method

from numba_dpex.experimental.core.types.kernel_api.items import (
    ItemType,
    NdItemType,
)
from numba_dpex.ocl._declare_function import _declare_function

from ..target import DPEX_KERNEL_EXP_TARGET_NAME


@intrinsic(target=DPEX_KERNEL_EXP_TARGET_NAME)
def _intrinsic_get_global_id(
    ty_context, ty_dim  # pylint: disable=unused-argument
):
    """Generates instruction for spirv i64 get_global_id(i32) call."""
    sig = types.int64(types.int32)

    def _intrinsic_exchange_gen(context, builder, sig, args):
        [dim] = args
        get_global_id = _declare_function(
            # unsigned int - is what demangler returns from IR instruction
            # generated by dpcpp. However int32 is passed as an argument.
            # Most likely it does not matter, since argument can be from 0 to 3.
            # TODO: https://github.com/IntelPython/numba-dpex/issues/936
            # Numba generates unnecessary checks because of the type mismatch.
            context,
            builder,
            "get_global_id",
            sig,
            ["unsigned int"],
        )
        res = builder.call(get_global_id, [dim])
        return context.cast(builder, res, types.uintp, types.intp)

    return sig, _intrinsic_exchange_gen


@overload_method(ItemType, "get_id", target=DPEX_KERNEL_EXP_TARGET_NAME)
def ol_item_get_id(item, dim):
    """SPIR-V overload for
    :meth:`numba_dpex.kernel_api.Item.get_id`.

    Generates the same LLVM IR instruction as dpcpp for the
    `sycl::item::get_id` function.

    Raises:
        TypingError: When argument is not an integer.
    """
    if not isinstance(item, ItemType):
        raise TypingError("Only Item is supported")

    if not isinstance(dim, types.Integer):
        raise TypingError("Only integers supported")

    # pylint: disable=unused-argument
    def ol_get_id(item, dim):
        # pylint: disable=no-value-for-parameter
        return _intrinsic_get_global_id(dim)

    return ol_get_id


@overload_method(
    NdItemType, "get_global_id", target=DPEX_KERNEL_EXP_TARGET_NAME
)
def ol_nd_item_get_global_id(nd_item, dim):
    """SPIR-V overload for
    :meth:`numba_dpex.kernel_api.NdItem.get_global_id`.

    Generates the same LLVM IR instruction as dpcpp for the
    `sycl::nd_item::get_global_id` function.

    Raises:
        TypingError: When argument is not an integer.
    """
    if not isinstance(nd_item, NdItemType):
        raise TypingError("Only NdItem is supported")

    if not isinstance(dim, types.Integer):
        raise TypingError("Only integers supported")

    # pylint: disable=unused-argument
    def ol_get_global_id(nd_item, dim):
        # pylint: disable=no-value-for-parameter
        return _intrinsic_get_global_id(dim)

    return ol_get_global_id
