# SPDX-FileCopyrightText: 2020 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

from numba import types
from numba.core.datamodel import default_manager, models
from numba.core.registry import cpu_target

from numba_dpex.core.datamodel.models import (
    DpnpNdArrayModel,
    USMArrayModel,
    dpex_data_model_manager,
)
from numba_dpex.core.descriptor import dpex_kernel_target
from numba_dpex.core.types.dpnp_ndarray_type import DpnpNdArray


def test_model_for_DpnpNdArray():
    """Test the datamodel for DpnpNdArray that is registered with numba's
    default datamodel manager and numba_dpex's kernel data model manager.
    """
    dpnp_ndarray = DpnpNdArray(ndim=1, dtype=types.float64, layout="C")
    model = dpex_data_model_manager.lookup(dpnp_ndarray)
    assert isinstance(model, USMArrayModel)
    default_model = default_manager.lookup(dpnp_ndarray)
    assert isinstance(default_model, DpnpNdArrayModel)


def test_dpnp_ndarray_Model():
    """Test for dpnp_ndarray_Model.

    It is a subclass of models.StructModel and models.ArrayModel.
    """

    assert issubclass(DpnpNdArrayModel, models.StructModel)


def test_flattened_member_count():
    """Test that the number of flattened member count matches the number of
    flattened args generated by the CpuTarget's ArgPacker.
    """

    cputargetctx = cpu_target.target_context
    kerneltargetctx = dpex_kernel_target.target_context
    dpex_dmm = kerneltargetctx.data_model_manager

    for ndim in range(4):
        dty = DpnpNdArray(ndim)
        argty_tuple = tuple([dty])
        datamodel = dpex_dmm.lookup(dty)
        num_flattened_args = datamodel.flattened_field_count
        ap = cputargetctx.get_arg_packer(argty_tuple)

        assert num_flattened_args == len(ap._be_args)
