name: Setup numba-dpex
description: 'Setup conda environment, build numba-dpex and setup devices'
inputs:
  # environment-file:
  environment:
    description: Environment file
    required: true
    default: environment/dev.yml
  environment-name:
    description: Environment name
    default: work-env
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        # mamba-version: "*"
        activate-environment: "${{ inputs.environment-name }}"
        channel-priority: "disabled"
        environment-file: "${{ inputs.environment }}"

    - name: Test conda environment
      shell: bash -l {0}
      run: conda list

    - name: Build numba-dpex
      shell: bash -l {0}
      run: |
        export PATH=$CONDA/bin-llvm:$PATH
        python setup.py develop

    - name: Setup OpenCL CPU device
      shell: bash -l {0}
      run: echo "OCL_ICD_FILENAMES=libintelocl.so" >> $GITHUB_ENV
